# Generated by Django 5.1.2 on 2025-03-23 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_user_password_consultation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Consultation",
        ),
    ]
